---
kind: pipeline
name: default

steps:
  - name: Go test
    image: golang:1.18
    environment:
      GO111MODULE: on
    commands:
      - go mod download
      - go test ./... --cover --count=100

  - name: "Bump & Tag"
    image: quay.io/openware/sdk-citools:2.6.7
    environment:
      BRANCH_NAME: ${DRONE_BRANCH}
      REPO_NAME: openware/rango
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:prebuild
    when:
      branch:
        - master
        - "*-stable"

  - name: Build container
    image: plugins/docker
    settings:
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      repo: quay.io/openware/rango
      registry: quay.io
    when:
      branch:
        - master
        - "*-stable"

  - name: "Update global OpenDAX version"
    image: quay.io/openware/goci:0.0.11
    environment:
      GIT_TOKEN:
        from_secret: gh_api_token
      GIT_USER:
        from_secret: gh_api_user
    commands:
      - export GIT_URL=https://${GIT_USER}:${GIT_TOKEN}@github.com/openware/versions-aurora.git
      - /app/goci versions
    when:
      branch:
        - "*-stable"
        - master

  - name: "Notify"
    image: quay.io/openware/sdk-citools:2.6.7
    environment:
      BOT_USERNAME: kite-bot
      BOT_NAME: Kite Bot
      BOT_EMAIL: kite-bot@heliostech.fr
      BRANCH_NAME: ${DRONE_BRANCH}
      REPO_NAME: ${DRONE_REPO}
      SDK_BRANCH: ${DRONE_BRANCH}
      SLACK_CHANNEL: peatio
      SLACK_TOKEN:
        from_secret: slack_token
      GITHUB_API_KEY:
        from_secret: kite_bot_key
      TELEGRAM_BOT_TOKEN:
        from_secret: telegram_bot_token
      TELEGRAM_CHAT_ID:
        from_secret: telegram_chat_id
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:postbuild[/drone/src]
    when:
      branch:
        - master
        - "*-stable"

  - name: Slack Notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel:
        from_secret: slack_webhook_channel
      template: >
        *{{uppercasefirst repo.name}}*
        {{#success build.status}}
          [SUCCESS] Branch {{ build.branch }} by {{ build.author }}. Good job.
        {{else}}
          [FAILURE] Branch {{ build.branch }} by {{ build.author }}. Fix me please.
        {{/success}}
    when:
      branch:
        - master
        - "*-stable"

trigger:
  event:
    - push

image_pull_secrets:
  - dockerconfigjson
